name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    container: onkwon/yaos:0.7
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Compile
        run: make all_devices
      - name: Install test framework
        run: make -C tests install
      - name: Test
        run: make -C tests
      - name: Build coverage results
        run: |
          make -C tests gcov
          mkdir -p coverage_report
          cd coverage_report
          cp -R ../tests/gcov/*.gcov ./
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage_report
      - name: codecov
        run: |
          bash -c "bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}"

  sonarCloud:
    name: SonarCloud Scan
    needs: build
    runs-on: ubuntu-latest
    container: onkwon/yaos:0.7
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: coverage_report
      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          build-wrapper-linux-x86-64 --out-dir bw-output \
              make all_devices
          sonar-scanner \
              -Dsonar.organization=onkwon-github \
              -Dsonar.projectKey=onkwon_libabov \
              -Dsonar.sources=arch,devices,hal,examples,include \
              -Dsonar.tests=tests \
              -Dsonar.test.inclusions=**/*_test.cpp \
              -Dsonar.cfamily.gcov.reportsPath=coverage_report \
              -Dsonar.cfamily.build-wrapper-output=bw-output \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
